site_name: investigraph
site_url: https://docs.investigraph.dev
repo_url: https://github.com/dataresearchcenter/investigraph
nav:
  - Intro: index.md
  - tutorial.md
  - install.md
  - Building datasets:
      - build/index.md
      - build/config.md
      - Stages:
        - stages/seed.md
        - stages/extract.md
        - stages/transform.md
        - stages/load.md
        - stages/export.md
      - Best practices:
        - Overview: how-to/index.md
        - Dataset metadata: how-to/metadata.md
        - Transform patterns: how-to/transform.md
        - Entity keys: how-to/keys.md
        - Utility functions: how-to/utils.md
  - Running datasets:
    - Command line: run/cli.md
    - Docker build: run/docker.md
    - Github Actions: run/actions.md
    - run/parallelization.md
  - Reference:
      - reference/helpers.md
      - reference/config.md
      - reference/source.md
      - Command line: reference/cli.md
      - reference/context.md
      - reference/settings.md
      - reference/types.md
  - Concepts:
      - concepts/catalog.md
      - concepts/dataset.md
      - concepts/entity.md
  - Stack:
      - stack/runpandarun.md
      - stack/followthemoney.md
      - stack/nomenklatura.md
theme:
  name: material
  logo: https://cdn.investigativedata.org/style/logos/darc/svg/DARC-Logo-RGB-Horizontal-Neg.svg
  favicon: https://cdn.investigativedata.org/style/logos/darc/favicon.ico
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    # - navigation.footer
    - toc.follow
    - content.code.copy
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: material/mail
      link: mailto:hi@dataresearchcenter.org
    - icon: material/web
      link: https://dataresearchcenter.org
    - icon: material/github
      link: https://github.com/openaleph/openaleph-procrastinate
    - icon: material/linkedin
      link: https://www.linkedin.com/company/dataresearchcenter/
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search
  - autorefs
  - mkdocs-typer2:
      pretty: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: false
            show_object_full_path: false
